baseurl = "http://www.blog.zstat.pl/"
relativeurls = true
languageCode = "en-us"
title = "zstat.pl - blog"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-80778306-3"
disqusShortname = "blog-zstat"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"

[params]
    description = "zstat.pl blog"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

