baseurl = "https://www.zstat.pl/"
relativeurls = true
languageCode = "en-us"
title = "zstat.pl - blog"
theme = "hugo-nuo-modif"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", "data"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    description = "Blog about R, Scala, Shiny, Spark, statistics, data science, machine learning and other stuff."
    avatar = "/img/zstat_logo_final.png"
    googleSiteVerification = "1jGcsgBOFOechhTDX8jgbvZAwO5_6iYBOu9LZTSs5cI"

    email = "zygmunt@zstat.pl"
    github = "zzawadz"
    twitter = "zzawadz"
    linkedin = "zygmunt-zawadzki-81525b92"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "scala", "cpp", "python"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)

    # How many posts to show on the sidebar (Default: 5)
    num_recent_posts = 5

[[languages.en.menu.main]]
  name = "Blog"
  weight = 10
  identifier = "blog"
  url = "/"

[[languages.en.menu.main]]
  name = "Tags"
  weight = 20
  identifier = "tags"
  url = "/tags/"

[[languages.en.menu.main]]
  name = "Data Scientist in Supply Chain"
  weight = 60
  identifier = "supply-chain"
  url = "/supply-chain/"
