baseurl = "https://www.zstat.pl/"
relativeurls = true
languageCode = "en-us"
title = "zstat.pl - blog"
theme = "hugo-lithium-theme"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/zzawadz"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/zygmunt-zawadzki-81525b92/"

[params]
    description = "zstat.pl blog"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

